### ISSUE TITLE
Remove custom Table of Content sections

### ISSUE THREAD

**Issue by rogeruiz** [trussworks/Engineering-Playbook#254]
The markdown pages in this repository post the Docusaurus migration contain comments with `mdformat-toc start`. These are no longer relevant as Docusaurus provides a response table of contents automatically.

**Comment by rogeruiz** [comment]
Here's the current breakdown of where these currently exist.

```
docs/infrasec/good-infra.md
docs/infrasec/aws/vpcs.md
docs/infrasec/aws/sns-guardduty-alert-integrations.md
docs/infrasec/aws/aws-organizations.md
docs/infrasec/aws/naming.md
docs/developing/vcs/master-to-main.md
docs/infrasec/aws/guardduty.md
docs/developing/cicd/circleci-orbs.md
docs/developing/cicd/delivery-pipeline.md
docs/developing/cicd/intro.md
docs/infrasec/aws/org-bootstrap.md
docs/infrasec/aws/govcloud/gov-orgs.md
docs/developing/docker/README.md
docs/infrasec/pro-dev.md
docs/infrasec/teardown.md
docs/infrasec/terraform/terratest.md
docs/infrasec/tutorials/your_first_lambda_function.md
docs/infrasec/tutorials/yubikey-configuration.md
```

**Comment by rogeruiz** [comment]
Also, with this change we should remove the `mdformat-toc` from our pre-commits as well.

Here's another way to see what files need to be edited for this Issue.
https://github.com/trussworks/Engineering-Playbook/search?q=mdformat

**Comment by Prakharkarsh1** [comment]
Hii @rogeruiz i want to contribute to fix this issue

**Comment by rogeruiz** [comment]
Hey @Prakharkarsh1 thank you for expressing interest in our OSS project. Please submit a PR from a fork and we will continue from there. Keep in mind that smaller Pull Requests are much easier to review so don’t feel pressured to submit all the changes in one big PR. Thanks again!
